---
permalink: recover/recovery-deployment.html
sidebar: sidebar
keywords:
summary: 'If you lose your ONTAP tools for VMware vSphere setup, but have your ONTAP working, you can recover ONTAP tools for VMware vSphere setup using the ONTAP. When you lose the setup, bring down the setup gracefully.'
---
= Recover your ONTAP tools for VMware vSphere setup
:icons: font
:imagesdir: ../media/

[.lead]
If you lose your ONTAP tools for VMware vSphere setup, you can recover the ONTAP tools for VMware vSphere setup using the data available in the ONTAP volume data.
When you lose the setup, bring down the setup gracefully.

[NOTE]
You cannot recover your ONTAP tools for VMware vSphere setup if there are issues with vCenter Server or ONTAP data management software. 

*Steps*

. Log in to the vSphere server.
. Navigate to the resource pool that you have created or to the node cluster or to the host where you want to deploy the OVA.
. Right-click the required location and select *Deploy OVF template*.
. Select the OVA file either through the URL for the _.ova_ file or browse to the folder where the _.ova_ file is saved, and then click *Next*.
+
[NOTE]
You should use the same OVA build that you used for installing the recovery setup.
. Select a name and folder for the virtual machine and select *Next*.
. Select the host and select *Next*.
. Review the summary of the template and select *Next*.
. Read and accept the license agreement and select *Next*.
. In the *Configuration* window, select *Recovery* option.
. In the *Select storage* window, select the storage for the configurations and disk files.
. In the *Select networks* window, select a destination network for each source network.
[NOTE]
You need to retain the load balancer IP address and the Kubernetes API Server IP address. You can change the node IP address or you can retain the same IP address.
. In the *Customize template* window, enter the required details and click *Next*
[NOTE]
When SVM scope is enabled you should have already enabled SVM support with management IP address.  
. Review the details in the *Ready to complete* window, select *Finish*.
+
As the deployment task gets created, the progress is shown in the vSphere task bar.
. Power on the VM after the completion of the task.
+
The installation begins. You can track the installation progress in VM’s web console.
As part of the installation, node configurations are validated. The inputs provided under different sections under the Customize template in the OVF form are validated. In case of any discrepancies, a dialog prompts you to take corrective action.
. Make necessary changes in the dialog prompt. Use tab button to navigate across the panel and select *OK*.
+
The values provided are validated again. ONTAP tools for VMware vSphere allows you three attempts to correct any invalid values. If you are unable  to correct issues after three attempts, the product installation stops and you are advised to try the installation on a fresh VM. 

After successful installation, the web console shows the state of ONTAP tools for VMware vSphere. 

After successful installation, you should manually edit the hardware requirements as per the guidelines in the link:../deploy/prerequisites.html[Prerequisites for deploying ONTAP tools for VMware vSphere] page. 
