---
permalink: protect/configure-protection-groups.html
sidebar: sidebar
keywords:
summary: 'You should create protection groups to protect a group of virtual machines on the protected site.'
---
= Configure protection groups
:icons: font
:imagesdir: ../media/

[.lead]
You should create protection groups to protect a group of virtual machines on the protected site.

*What you will need*

You should ensure that both the source and target sites are configured for the following:

* Same version of VMware Live Site Recovery installed
* Virtual machines
* Paired protected and recovery sites
* Source and destination datastores should be mounted on respective sites

*Steps*

. Log in to vCenter Server and then click *Site Recovery* > *Protection Groups*.
. In the *Protection Groups* pane, click *New*.
. Specify a name and description for the protection group, direction and click *Next*.
. In the *Type* field, select the *Type field option...* as Datastore groups (array-based replication) for NFS and VMFS datastore.
The fault domain is nothing but SVMs with replication enabled. The SVMs that have only peering implemented and have no issues are displayed.

. In the Replication groups tab, select either the enabled array pair or the replication groups that have the virtual machine you configured, and then click *Next*.
+
All the virtual machines on the replication group are added to the protection group.

. Select either the existing recovery plan or create a new plan by clicking *Add to new recovery plan*.
. In the Ready to complete tab, review the details of the protection group that you created, and then click *Finish*.
