---
permalink: protect/configure-on-srm-appliance.html
sidebar: sidebar
keywords:
summary: 'After you have deployed the VMware Live Site Recovery appliance, you should configure SRA on VMware Live Site Recovery appliance. The successful configuration of SRA enables VMware Live Site Recovery appliance to communicate with SRA for disaster recovery management. You should store ONTAP tools for VMware vSphere credentials \(IP address and administrator password\) in the VMware Live Site Recovery appliance to enable communication between VMware Live Site Recovery appliance and SRA.'
---
= Configure SRA on VMware Live Site Recovery appliance
:icons: font
:imagesdir: ../media/

[.lead]
After you have deployed the VMware Live Site Recovery appliance, you should configure SRA on VMware Live Site Recovery appliance. The successful configuration of SRA enables the VMware Live Site Recovery appliance to communicate with SRA for disaster recovery management. You should store ONTAP tools for VMware vSphere credentials (IP address) in the VMware Live Site Recovery appliance to enable communication between VMware Live Site Recovery appliance and SRA.

*What you will need*

You should have downloaded the _tar.gz_ file from https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab[NetApp Support Site].

*About this task*

The configuration of SRA on VMware Live Site Recovery appliance stores the SRA credentials in the VMware Live Site Recovery appliance.

*Steps*
//On vSphere client menu, click on NetApp ONTAP tools > Settings > Administrative Settings > Manage Capabilities > Enable Storage Replication Adapter (SRA) 
//Github issue 54, should i add it to 101 as well?

. On the VMware Live Site Recovery appliance screen, click *Storage Replication Adapter* > *New Adapter*.
. Upload the _.tar.gz_ file to VMware Live Site Recovery.
. Log in using administrator account to the VMware Live Site Recovery appliance using putty.
. Switch to the root user using the command: `su root`
. Run the command `cd /var/log/vmware/srm` to navigate to the log directory.
. At the log location, enter the command to get the docker ID used by SRA: `docker ps -l`
. To log in to the container ID, enter the command: `docker exec -it -u srm <container id> sh`
. Configure VMware Live Site Recovery with ONTAP tools for VMware vSphere IP address and password using the command: `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <Application username> --otv-password <Application password> --vcenter-guid <VCENTER_GUID>'`
[NOTE]
You need to provide the password value within single quotes to ensure that the Perl script does not read the special characters in the password as a delimiter of the input.
[NOTE]
The application username and password is set during the ONTAP tools deployment. This is needed for VASA provider/SRA registration.
. Rescan the adapters to verify that the details are updated on the VMware Live Site Recovery Storage Replication Adapters page.

A success message confirming that the storage credentials are stored is displayed. SRA can communicate with SRA server using the provided IP address, port and credentials.
