---
permalink: protect/configure-storage-replication-adapter-for-highly-scaled-environment.html
sidebar: sidebar
keywords:
summary: 'You should configure the storage timeout intervals per the recommended settings for Storage Replication Adapter \(SRA\) to perform optimally in highly scaled environments.'
---
= Configure SRA for highly scaled environments
:icons: font
:imagesdir: ../media/

[.lead]
You should configure the storage timeout intervals per the recommended settings for Storage Replication Adapter (SRA) to perform optimally in highly scaled environments.

== Storage Provider settings

You should set the following timeout values on VMware Live Site Recovery for scaled environment:

|===
| *Advanced settings*| *Timeout values*
a|
`StorageProvider.resignatureTimeout`
a|
Increase the value of the setting from 900 seconds to 12000 seconds.
a|
`storageProvider.hostRescanDelaySec`
a|
60
a|
`storageProvider.hostRescanRepeatCnt`
a|
20
a|
`storageProvider.hostRescanTimeoutSec`
a|
Set a high value (For example: 99999)
|===
You should also enable the `StorageProvider.autoResignatureMode` option.

See the VMware documentation for more information on modifying Storage Provider settings.

https://docs.vmware.com/en/VMware-Live-Site-Recovery/9.0/vmware-live-site-recovery/GUID-E4060824-E3C2-4869-BC39-76E88E2FF9A0.html[VMware vSphere Documentation: Change Storage Provider Settings]

== Storage settings

When you hit a timeout, increase the values of `storage.commandTimeout` and `storage.maxConcurrentCommandCnt` to a higher value.

NOTE: The timeout interval specified is the maximum value. You do not need to wait for the maximum timeout to be reached. Most commands finish within the set maximum timeout interval.

See the VMware documentation on modifying SAN Provider settings for more information.

https://docs.vmware.com/en/VMware-Live-Site-Recovery/9.0/vmware-live-site-recovery/GUID-711FD223-50DB-414C-A2A7-3BEB8FAFDBD9.html[VMware Site Recovery Manager Documentation: Change Storage Settings]
