---
permalink: protect/enable-storage-replication-adapter.html
sidebar: sidebar
keywords:
summary: 'ONTAP tools for VMware vSphere provides the option to enable the SRA capability to configure disaster recovery.'
---
= Enable SRA to protect datastores
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP tools for VMware vSphere provides the option to enable the SRA capability to configure disaster recovery.

*What you will need*

* You should have set up your vCenter Server instance and configured ESXi host.
* You should have deployed ONTAP tools.
* You should have downloaded the SRA Adapter `.tar.gz` file from the https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab[NetApp Support Site^].

*Steps*

. Log in to the VMware Live Site Recovery appliance management interface using the URL: `\https://:<srm_ip>:5480`, and then go to Storage Replication Adapters in VMware VMware Live Site Recovery appliance management interface.
. Select *New Adapter*.
. Upload the _.tar.gz_ installer for the SRA plug-in to VMware Live Site Recovery.
. Rescan the adapters to verify that the details are updated on the VMware Live Site Recovery Storage Replication Adapters
page.

