---
permalink: protect/map-network.html
sidebar: sidebar
keywords:
summary: 'You should map your networks on the protected site and the recovery site to enable communication between them.'
---
= Configure network mappings
:icons: font
:imagesdir: ../media/

[.lead]
You should configure your resource mappings like VM networks, ESXi hosts, and folders on both sites to enable the mapping of each resource from the protected site to the appropriate resource at the recovery site.

You should complete the following resource configurations:

* Network mappings
* Folder mappings
* Resource mappings
* Placeholder datastores

*What you will need*

You should have connected the protected and recovery sites.

*Steps*

. Log in to vCenter Server and click on *Site Recovery* > *Sites*.
. Select your protected site and click *Manage*.
. In the Manage tab, select *Network Mappings*.
. Click *New* to create a new network mapping.
+
The Create Network Mapping wizard appears.

. In the Create Network Mapping wizard, perform the following:
 .. Select *Automatically Prepare Mappings for Networks with Matching Names* and click *Next*.
 .. Select the required data center objects for the protected and recovery sites and click *Add Mappings*.
 .. Click *Next* after mappings are created successfully.
 .. Select the object used earlier to create reverse mapping, then click *Finish*.

*Result*

The Network Mappings page displays the protected site resources and the recovery site resources. You can follow the same steps for other networks in your environment.
