---
permalink: configure/create-vvols-datastore.html
sidebar: sidebar
keywords:
summary: 'You can create vVols datastore with new volumes or with existing volumes. You can also create vVols datastore with the combination of existing volumes and new volumes.'
---
= Create a datastore
:icons: font
:imagesdir: ../media/

[.lead]

When you create a datastore at host cluster level, the datastore is created and mounted on all the hosts of the destination and the action is enabled only if the current user has privilege to execute.

The create Datastore action wizard supports creation of NFS, VMFS, and vVols datastore.

[NOTE]
* You can create only VMFS datastores on a protected cluster. When you add a VMFS datastore to a protected cluster, the datastore becomes protected automatically. 
* You cannot create a datastore on a datacenter that has one or more protected host clusters.
* You cannot create a datastore at host if the parent host cluster is protected with a relationship of Automated Failover Duplex policy type (uniform/non-uniform config).
* You can create a VMFS datastore on a host, only when it has an async relationship. 

//10.2 updates - notes

[role="tabbed-block"]
====

.Create a vVols datastore
--

You can create a vVols datastore with either new volumes or existing volumes. You cannot create vVols datastore with the mix of existing and new volumes.
[NOTE]
Check to ensure root aggregates are not mapped to SVM.

.Before you begin
Ensure that VASA provider is registered with the selected vCenter.

.Steps
. Log in to the vSphere client using `\https://vcenterip/ui`
. Right-click a host system or a host cluster or a datacenter and select *NetApp ONTAP tools* > *Create Datastore*.
. In the *Type* pane, select vVols in *Datastore Type*.
. In the *Name and Protocol* pane, provide *Datastore name* and *Protocol* information.
. In the *Storage* pane, select *Platform* and *storage VM*. In the *Advanced options* section, select custom export policy (for NFS protocol) or custom initiator group name (for iSCSI amd FC protocol) as applicable.
[NOTE]
* Platform and asymmetric options help you to filter out the SVMs dropdown options. You should select the SVM to create or use the volume(s) for datastore creation. 
* The *Asymmetric* toggle button is visible only if iSCSI was selected in the previous step and performance or capacity is selected in the platform drop-down.
* Select the *Asymmetric* toggle button for AFF platform and disable it for ASA platform.
. In the *Storage attributes* pane, you can either create new volumes or use the existing volumes. When creating new volume, you can enable QoS on the datastore.
. Review your selection in the *Summary* pane and click *Finish*.
The vVols Datastore is created and mounted on all the hosts.

--

.Create an NFS datastore

--
//10.1 addition
A VMware Network File System (NFS) datastore uses the NFS protocol to connect ESXi hosts to a shared storage device over a network. NFS datastores are commonly used in VMware vSphere environments and offer several advantages, such as simplicity and flexibility.

.Steps
. Log in to the vSphere client using `\https://vcenterip/ui`
. Right-click a Host System or a Host Cluster or a Datacenter and select *NetApp ONTAP tools* > *Create Datastore*.
. In the *Type* pane, select NFS in *Datastore Type*.
. In the *Name and Protocol* pane, enter datastore name, size, and protocol information. In the advanced options, select *Datastore cluster* and *Kerberos Authentication*.
[NOTE]
Kerberos Authentication is available only when the NFS 4.1 protocol is selected. 
. In the *Storage* pane, select *Platform* and *Storage VM*. You can select *custom Export Policy* in the *Advanced Option* section.
[NOTE]
* *Asymmetric* toggle button is visible only if performance or capacity is selected in the platform drop-down.
* *Any* option in the platform dropdown enables you to see all the SVMs that are part of the vCenter irrespective of the platform or asymmetric flag. 
. In the *Storage Attributes* pane, select the aggregate for creation of volume. In the advanced options choose *Space Reserve* and *Enable QoS* as required.
. Review the selections in the *Summary* pane and click *Finish*.

The NFS datastore is created and mounted on all the hosts.

--

.Create a VMFS datastore

--
Virtual Machine File System (VMFS) is a clustered file system specifically designed for storing virtual machine files in VMware vSphere environments. It allows multiple ESXi hosts to access the same virtual machine files concurrently, enabling features like vMotion and High Availability.

.Before you begin

Check the following items before proceeding:

* For each protocol on ONTAP storage side, respective services and LIF’s need to be enabled. 
* If you are using the NVMe/TCP protocol, perform the following steps to configure the ESXi host:

. Review the https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc[VMware Compatibility Guide]
[NOTE] 
VMware vSphere 7.0 U3 and later versions support NVMe/TCP protocol. However, VMware vSphere 8.0 and later version is recommended. 
. Validate if the Network Interface Card (NIC) vendor supports ESXi NIC with NVMe/TCP protocol. 
. Configure the ESXi NIC for NVMe/TCP according to the NIC vendor specifications. 
. When using VMware vSphere 7 release, follow the instructions on the VMware site https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-D047AFDD-BC68-498B-8488-321753C408C2.html#GUID-D047AFDD-BC68-498B-8488-321753C408C2[Configure VMkernel Binding for the NVMe over TCP Adapter] to configure NVMe/TCP port binding. When using VMware vSphere 8 release, follow https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-storage/GUID-5F776E6E-62B1-445D-854C-BEA689DD4C92.html#GUID-D047AFDD-BC68-498B-8488-321753C408C2[Configuring NVMe over TCP on ESXi], to configure the NVMe/TCP port binding. 
. For VMware vSphere 7 release, follow the instructions on the VMware site https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-8BBD672E-0829-4CF2-84B2-26A3A89ABD2E.html[Enable NVMe over RDMA or NVMe over TCP Software Adapters] to configure NVMe/TCP software adapters. For VMware vSphere 8 release, follow https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-storage/GUID-F4B42510-9E6D-4446-816A-5012866E0038.html#GUID-8BBD672E-0829-4CF2-84B2-26A3A89ABD2E[Add Software NVMe over RDMA or NVMe over TCP Adapters] to configure the NVMe/TCP software adapters.
. Run link:../configure/discover-storage-systems-and-hosts[Discover storage systems and hosts] action on the ESXi host.
For more information, refer to https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429[How to Configure NVMe/TCP with vSphere 8.0 Update 1 and ONTAP 9.13.1 for VMFS Datastores] 

* If you are using the NVME/FC protocol, perform the following steps to configure the ESXi host:
. Enable NVMe over Fabrics(NVMe-oF) on your ESXi host(s). 
. Complete SCSI zoning. 
. Ensure that ESXi hosts and the ONTAP system are connected at a physical and a logical layer.

To configure an ONTAP SVM for FC protocol, refer to https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html[Configure an SVM for FC].

For more information on using NVMe/FC protocol with VMware vSphere 8.0, refer to https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html[NVMe-oF Host Configuration for ESXi 8.x with ONTAP].

For more information on using NVMe/FC with VMware vSphere 7.0, refer to https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html[ONTAP NVMe/FC Host Configuration guide] and http://www.netapp.com/us/media/tr-4684.pdf[TR-4684].

.Steps
. Log in to the vSphere client using `\https://vcenterip/ui`
. Right-click a Host System or a Host Cluster or a Datastore and select *NetApp ONTAP tools* > *Create Datastore*.
. In the *Type* pane, select VMFS in *Datastore Type*.
. In the *Name and Protocol* pane, enter the datastore name, size, and protocol information. In the *Advanced options* section of the pane, select the Datastore cluster you want to add this datastore to. 
. Select Platform and storage VM in the *Storage* pane. Select the Asymmetric toggle button. Provide the *Custom initiator group name* in the *Advanced options* section of the pane (optional). You can either choose an existing igroup for the datastore or create a new igroup with a custom name.
+
If you choose the *Any* option in the platform dropdown you can see all the SVMs that are part of the vCenter irrespective of the platform or asymmetric flag.
When the protocol is selected as NVMe/FC or NVMe/TCP, a new namespace subsystem is created and is used for namespace mapping. By default, the namespace subsystem is created using the auto generated name that includes the datastore name. You can rename the namespace subsystem in the *custom namespace subsystem name* field in the advanced options of *Storage* pane. 
. From the *storage attributes* pane, select *Aggregate* from the drop-down menu. Select *Space Reserve*, *Use existing volume*, and *Enable QoS* options as required from the *Advanced options* section and provide the details as required.
+
[NOTE]
For VMFS datastore creation with NVMe/FC or NVMe/TCP protocol you cannot use the existing volume, you should create new volume.
//10.2 update
. Review the datastore details in the *Summary* pane and click *Finish*.
+
[NOTE]
If you're creating the datastore on a protected cluster, you can see a readonly message "The datastore is being mounted on a protected Cluster."
The VMFS datastore is created and mounted on all the hosts.

--