---
permalink: configure/discover-storage-systems-and-hosts.html
sidebar: sidebar
keywords:
summary: 'When you first run ONTAP tools for VMware vSphere in a vSphere Client, ONTAP tools for VMware vSphere discovers the ESXi hosts, their LUNs and NFS exports, and the NetApp storage systems that own those LUNs and exports.'
---
= Discover storage systems and hosts
:icons: font
:imagesdir: ../media/

[.lead]
When you first run ONTAP tools for VMware vSphere in a vSphere Client, ONTAP tools discovers the ESXi hosts, their LUNs and NFS exports, and the NetApp storage systems that own those LUNs and exports.

*What you will need*

* All the ESXi hosts should be powered on and connected.
* All the storage virtual machines (SVMs) to be discovered should be running, and each cluster node should have at least one data LIF configured for the storage protocol in use (NFS or iSCSI).

*About this task*

You can discover new storage systems or update information about existing storage systems to obtain the latest capacity and configuration information at any time. You can also modify the credentials that ONTAP tools for VMware vSphere uses to log in to the storage systems.

While discovering the storage systems, ONTAP tools for VMware vSphere collects information from the ESXi hosts that are managed by the vCenter Server instance.

*Steps*

. From the vSphere Client home page, select *Hosts and Clusters*.
. Right-click the required datacenter and select *NetApp ONTAP tools* > *Update Host Data* .
+
ONTAP tools for VMware vSphere displays a *Confirm* dialog box with the following message: 
+
"This action will restart the discovery of all connected storage systems and might take a few minutes. Do you want to continue?"
. Click *Yes*.
. Select the discovered storage controllers that have the status `Authentication Failure` and click *Actions* > *Modify*.
. Fill in the required information in the *Modify Storage System* dialog box.
+
. Repeat steps 4 and 5 for all storage controllers with `Authentication Failure` status.

After the discovery process is complete, perform the following actions:

* Use ONTAP tools for VMware vSphere to configure ESXi host settings for hosts that display the Alert icon in the Adapter Settings column, the MPIO Settings column, or the NFS Settings column.
* Provide the storage system credentials.
