---
permalink: configure/esxi-host-values.html
sidebar: sidebar
keywords:
summary: 'You can set timeouts and other values on the ESXi hosts using ONTAP tools for VMware vSphere to ensure best performance and successful failover. The values that ONTAP tools for VMware vSphere sets are based on internal NetApp testing.'
---
= Set ESXi host values
:icons: font
:imagesdir: ../media/

[.lead]
You can set timeouts and other values on the ESXi hosts using ONTAP tools for VMware vSphere to ensure best performance and successful failover. The values that ONTAP tools for VMware vSphere sets are based on internal NetApp testing.

You can set the following values on an ESXi host:

== HBA/CNA Adapter Settings
Sets the recommended HBA timeout settings for NetApp storage systems.

* *Disk.QFullSampleSize*
+
Set this value to 32 for all configurations. Setting this value helps to prevent I/O errors.

* *Disk.QFullThreshold*
+
Set this value to 8 for all configurations. Setting this value helps prevent I/O errors.

* *Emulex FC HBA timeouts*
+
Use the default value.

* *QLogic FC HBA timeouts*
+
Use the default value.

== MPIO Settings

MPIO settings define preferred paths for NetApp storage systems. The MPIO settings determine which of the available paths are optimized (as opposed to non-optimized paths that traverse the interconnect cable) and they set the preferred path to one of those paths.

In high-performance environments, or when you are testing performance with a single LUN datastore, consider changing the load balance setting of the round-robin (VMW_PSP_RR) path selection policy (PSP) from the default IOPS setting of 1000 to a value of 1.

== NFS settings

* *Net.TcpipHeapSize*
+
Set this value to 32.
* *Net.TcpipHeapMax*
+
Set this value to 1024MB.
* *NFS.MaxVolumes*
+
Set this value to 256.
* *NFS41.MaxVolumes*
+
Set this value to 256.
* *NFS.MaxQueueDepth*
+
Set this value to 128 or higher to avoid queuing bottlenecks.
* *NFS.HeartbeatMaxFailures*
+
Set this value to 10 for all NFS configurations.
* *NFS.HeartbeatFrequency*
+
Set this value to 12 for all NFS configurations.
* *NFS.HeartbeatTimeout*
+
Set this value to 5 for all NFS configurations.
