---
permalink: configure/esxi-host-values.html
sidebar: sidebar
keywords:
summary: 'You can set timeouts and other values on the ESXi hosts using ONTAP tools for VMware vSphere to ensure best performance and successful failover. The values that ONTAP tools for VMware vSphere sets are based on internal NetApp testing.'
---
= Set ESXi host values
:icons: font
:imagesdir: ../media/

[.lead]
You can set timeouts and other values on the ESXi hosts using ONTAP tools for VMware vSphere to ensure best performance and successful failover. The values that ONTAP tools for VMware vSphere sets are based on internal NetApp testing.

You can set the following values on an ESXi host:

== HBA/CNA Adapter Settings
Sets the following parameters to default values: 

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Emulex FC HBA timeouts
* QLogic FC HBA timeouts
// OTVDOC-267 - jani

== MPIO Settings

MPIO settings define preferred paths for NetApp storage systems. The MPIO settings determine which of the available paths are optimized (as opposed to non-optimized paths that traverse the interconnect cable) and they set the preferred path to one of those paths.

In high-performance environments, or when you are testing performance with a single LUN datastore, consider changing the load balance setting of the round-robin (VMW_PSP_RR) path selection policy (PSP) from the default IOPS setting of 1000 to a value of 1.

[NOTE]
The MPIO settings do not apply to NVMe, NVMe/FC, and NVMe/TCP protocols.
// OTVDOC-281 updates -Jani

== NFS settings

* *Net.TcpipHeapSize*
+
Set this value to 32.
* *Net.TcpipHeapMax*
+
Set this value to 1024MB.
* *NFS.MaxVolumes*
+
Set this value to 256.
* *NFS41.MaxVolumes*
+
Set this value to 256.
* *NFS.MaxQueueDepth*
+
Set this value to 128 or higher to avoid queuing bottlenecks.
* *NFS.HeartbeatMaxFailures*
+
Set this value to 10 for all NFS configurations.
* *NFS.HeartbeatFrequency*
+
Set this value to 12 for all NFS configurations.
* *NFS.HeartbeatTimeout*
+
Set this value to 5 for all NFS configurations.
