---
permalink: configure/install-nfs-vaai-plug-in.html
sidebar: sidebar
keywords:
summary: 'You can install the NetApp NFS Plug-in for VMware vStorage APIs for Array Integration \(VAAI\) using ONTAP tools for VMware vSphere.'
---
= Install the NFS VAAI plug-in
:icons: font
:imagesdir: ../media/

[.lead]
You can install the NetApp NFS Plug-in for vSphere APIs for Array Integration (VAAI) using ONTAP tools for VMware vSphere.

*What you will need*

* You should have downloaded the installation package for the NFS Plug-in for VAAI (`.vib`) from the NetApp Support Site. https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab[NetApp NFS Plug-in for VMware VAAI]
* You should have installed ESXi host 7.0U3 latest patch as minimum version and ONTAP 9.12.1Px (latest P release) 9.13.1Px, 9.14.1Px, or later.
* You should have powered on the ESXi host and mounted an NFS datastore.
* You should have set the values of the `DataMover.HardwareAcceleratedMove`, `DataMover.HardwareAcceleratedInit`, and `VMFS3.HardwareAcceleratedLocking` host settings to "`1`".
+
These values are set automatically on the ESXi host when the Recommended Settings dialog box is updated.

* You should have enabled the vstorage option on the storage virtual machine (SVM) by using the `vserver nfs modify -vserver vserver_name -vstorage enabled` command.
* You should have ESXi 7.0U3 or later if you are using NetApp NFS VAAI plug-in 2.0.
* You should have the vSphere 7.0U3 latest patch releases as vSphere 6.5 has been deprecated.
* vSphere 8.x is supported with the NetApp NFS VAAI plug-in 2.0.1(build 16).

*Steps*

. Click *Settings* from the ONTAP tools for VMware vSphere home page.
. Click *NFS VAAI Tools* tab.
. When the VAAI plug-in is uploaded to vCenter Server, select *Change* in the *Existing version* section. If a VAAI plug-in is not uploaded to the vCenter Server, select *Upload* button.
. Browse and select the `.vib` file and click *Upload* to upload the file to ONTAP tools.
. Click *Install on ESXI host*, select the ESXi host on which you want to install the NFS VAAI plug-in, and then click *Install*.
+
Only the ESXi hosts that are eligible for the plug-in installation are displayed. You should follow the on-screen instructions to complete the installation. You can monitor the installation progress in the Recent Tasks section of vSphere Web Client. 
. You should manually reboot the ESXi host after the installation finishes.
+
When the VMware admin reboots the ESXi host, ONTAP tools for VMware vSphere automatically detect the NFS VAAI plug-in. You do not have to perform additional steps to enable the plug-in.

=== Configure the correct NFS export policies for VAAI copy offload

When configuring VAAI in a NFS environment, export policy rules should be configured with the following requirements in mind:

* The relevant volume needs to allow the NFSv4 calls.
* The root user should remain as root and NFSv4 should be allowed in all junction parent volumes.
* The option for VAAI support needs to be set on the relevant NFS server.

For more information on the procedure, refer to https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload[Configure the correct NFS export policies for VAAI copy offload] KB article.

// added as part of github issue https://github.com/NetAppDocs/ontap-tools-vmware-vsphere-10/issues/13