---
permalink: manage/configure-remote-diagnostic-access.html
sidebar: sidebar
keywords:
summary: 'You can configure ONTAP tools for VMware vSphere to enable SSH access for the diag user.'
---
= Configure remote diagnostic access
:icons: font
:imagesdir: ../media/

[.lead]
You can configure ONTAP tools for VMware vSphere to enable SSH access for the diag user.

*What you will need*

The VASA Provider extension should be enabled for your vCenter Server instance.

*About this task*

Using SSH to access the diag user account has the following limitations:

* You are allowed only one login account per activation of SSH.
* SSH access to the diag user account is disabled when one of the following happens:
 ** The time expires.
+
The login session remains valid only till midnight the next day.

 ** You log in as a diag user again using SSH.

*Steps*

. From vCenter Server, open a console to VASA Provider.
. Log in as the maintenance user.
. Enter `4` to select Support and Diagnostics.
. Enter `2` to select Enable remote diagnostics access.
. Enter `y` in the Confirmation dialog box to enable remote diagnostic access.
. Enter a password for remote diagnostic access.
