---
permalink: manage/edit-esxi-host-settings.html
sidebar: sidebar
keywords:
summary: 'You can use the dashboard of ONTAP tools for VMware vSphere to edit your ESXi host settings.'
---
= Modify ESXi host settings using ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You can use the dashboard of ONTAP tools for VMware vSphere to edit your ESXi host settings.

*What you will need*

If there is an issue with your ESXi host settings, the issue is displayed in the ESXi host systems portlet of the dashboard. You can click the issue to view the host name or the IP address of the ESXi host that has the issue.

*Steps*

. Log in to the vSphere client using `\https://vcenterip/ui`
. In the shortcuts page, click on *NetApp ONTAP tools* under the plug-ins section.
. Go to *ESXi Host compliance* portlet in the Overview (Dashboard) of the ONTAP tools for VMware vSphere plug-in.
. Select *Apply Recommended Settings* link.
. In the *Apply recommended host settings* window, select the hosts that you want to comply with NetApp recommended host settings and click *Next*.
[NOTE]
You can expand the ESXi host to see the current values.
. In the settings page, select the recommended values as required.
. In the summary pane, check the values and click *Finish*.
You can track the progress in the Recent task panel.