---
permalink: manage/expand-storage-of-vvol-datastore.html
sidebar: sidebar
keywords: virtual volume datastores
summary: 'When you right click on datastore object in the vCenter object view, ONTAP tools for VMware vSphere supported actions are shown under the plug-in section.'
---
= Expand vVols Datastore
:icons: font
:imagesdir: ../media/

[.lead]

When you right click on datastore object in the vCenter object view, ONTAP tools for VMware vSphere supported actions are shown under the plug-in section. Specific actions are enabled depending on the type of datastore and the current user privileges.

*Steps*

. From the vSphere Client home page, click *Hosts and Clusters*.
. In the navigation pane, select the datacenter that contains the datastore.
. Right-click the datastore and select *NetApp ONTAP tools* > *Add storage to datastore*.
. In the *create or Select Volumes* window, you can either create new volumes or choose from the existing volumes. The UI is self-explanatory. Follow the instructions as per your choice.
. In the *Summary* window, review the selections and click *Expand*.
You can track the progress in the Recent Tasks panel.