---
permalink: manage/igroup-management.html
sidebar: sidebar
keywords:
summary: 'In ONTAP, export polices are used to provide volume data path access to hosts and igroups are used to provide LUN data path access to ESXi hosts.'
---
= Manage igroups and export policies
:icons: font
:imagesdir: ../media/

[.lead]
In ONTAP, export polices are used to provide volume data path access to hosts and initiator groups (igroups) are used to provide logical unit number (LUN) data path access to ESXi hosts. ONTAP tools for VMware vSphere makes igroup creation easy and intuitive and provides rich end-to-end workflows. To ensure consistency, direct  iGroup creation on storage platforms is not supported.

When virtual volume datastores are created or mounted to hosts in vCenter Server, the hosts need to be given access to volumes (NFS) or LUNs (iSCSI) depending on the protocol type of the datastore.

The export policy is dynamic and the new export policy is created with the naming format of trident-uuid. On your ONTAP System Manager, go to *Storage* > *Storage VMs* > *[storage VM name]* > *Settings* > *Export Policies* to see the export policy.

The igroups and export policies in ONTAP tools for VMware vSphere are managed in an efficient manner and provide the following benefits:

* Supports migrated export policies and igroups.
* No interruption of virtual machine input and output operations.
* Supports mounting on additional hosts without manual intervention.
* Minimizes the need for managing the number of igroups and export policies.
* A garbage collector automatically deletes all the unused managed igroups and export policies periodically.
* If a datastore is provisioned at the host cluster level, then igroup is created with all host initiators under the host cluster that are added to the igroup.
