---
permalink: manage/manage-vcenter.html
sidebar: sidebar
keywords:
summary: 'vCenters are central management platforms that allow you to control hosts, virtual machines, and storage backends.'
---
= Manage vCenter Server instances
:icons: font
:imagesdir: ../media/

[.lead]
vCenter Server instances are central management platforms that allow you to control hosts, virtual machines, and storage backends.

== Associate or dissociate storage backends with vCenter Server instance

The vCenter Server listing page shows the associated number of storage backends. Each vCenter Server instance has the option to associate or disassociate a storage backend.
This task helps you to create mapping between storage backend and onboarded vCenter Server instance globally.

*Steps*

. Launch ONTAP tools Manager from a web browser: `\https://loadBalanceIP:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the required vCenter Server instance from the sidebar.
. Click on the vertical ellipses against the vCenter Server that you want to associate or dissociate with storage backends.
. Select *Associate or Dissociate storage backend* depending on what action you want to perform.

== Modify a vCenter Server instance
Follow the steps below to modify a vCenter Server instances.

. Launch ONTAP tools Manager from a web browser: `\https://loadBalanceIP:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the applicable vCenter Server instance from the sidebar
. Click on the vertical ellipses against the vCenter Server that you want to modify and select *Modify*.
. Modify the vCenter Server instance details and select *Modify*.

== Remove a vCenter Server instance
You need to remove all the storage backends attached to the vCenter Server before removing it. 

. Launch ONTAP tools Manager from a web browser: `\https://loadBalanceIP:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the applicable vCenter Server instances from the sidebar
. Click on the vertical ellipses against the vCenter Server that you want remove and select *Remove*.
+
[NOTE]
Once you remove vCenter Server instances, they will no longer be maintained by the application.

When you remove vCenter Server instances in ONTAP tools, the following actions are performed automatically: 

* Plug-in is unregistered.
* Plug-in privileges and plug-in roles are removed.
