---
permalink: manage/storage-backend.html
sidebar: sidebar
keywords:
summary: 'Storage backends are systems that the ESXi hosts use for data storage.'
---
= Manage storage backends
:icons: font
:imagesdir: ../media/

[.lead]
Storage backends are systems that the ESXi hosts use for data storage.

== Discover storage

You can run the discovery of a storage backend on demand without waiting for a scheduled discovery to update the storage details.

Follow the steps below to discover the storage backends.

.Steps

. Log in to the vSphere client using `\https://vcenterip/ui`
. In the shortcuts page, click on *NetApp ONTAP tools* under the plug-ins section.
. In the left pane of ONTAP tools, navigate to *Storage Backends* and select a storage backend.
. Click on the vertical ellipses menu and select *Discover storage*

You can track the progress in the Recent Tasks panel.

== Modify storage backends
Follow the steps in this section to modify a storage backend.

. Log in to the vSphere client using `\https://vcenterip/ui`
. In the shortcuts page, click on *NetApp ONTAP tools* under the plug-ins section.
. In the left pane of ONTAP tools, navigate to *Storage Backends* and select a storage backend.
. Click on the vertical ellipses menu and select *Modify* to modify the credentials or the port name.
You can track the progress in the Recent Tasks panel.

You can perform the Modify operation for global ONTAP clusters using ONTAP tools Manager using the following steps.

. Launch ONTAP tools Manager from a web browser: `\https://loadBalanceIP:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select storage backends from the sidebar.
. Select the Storage Backend you want to modify.
. Click on the vertical ellipses menu and select *Modify*. 
. You can modify the credentials or the port. Enter the *Username* and *Password* to modify the storage backend.

== Remove storage backends

You need to delete all the datastores attached to the storage backend before removing the storage backend. 
Follow the steps below to remove a storage backend.

. Log in to the vSphere client using `\https://vcenterip/ui`
. In the shortcuts page, click on *NetApp ONTAP tools* under the plug-ins section.
. In the left pane of ONTAP tools, navigate to *Storage Backends* and select a storage backend.
. Click on the vertical ellipses menu and select *Remove*. Ensure that the storage backend does not contain any datastores.
You can track the progress in the Recent Tasks panel.

You can perform the remove operation for global ONTAP clusters using ONTAP tools Manager.

. Launch ONTAP tools Manager from a web browser: `\https://loadBalanceIP:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select *Storage Backends* from the sidebar.
. Select the storage backend you want to remove
. Click on the vertical ellipses menu and select *Remove*. 

== Drill down view of storage backend

The storage backend page lists all the storage backends. You can perform discover storage, modify, and remove operations on the storage backends you added and not the individual child under the cluster. 

When you click on either the parent cluster or the child under the storage backend, you can see the overall summary of the component. When you click on the parent cluster you have the actions dropdown from which you can perform the discover storage, modify, and remove operations. This option is missing when you click on the child SVM. 

The summary page provides the following details:

* Status of the storage backend
* Capacity information
* Basic information about the VM
* Network information like the IP address and port of the network. For the child SVM, the information will be same as the parent storage backend.
* Privileges allowed and restricted for the storage backend. For the child SVM, the information will be same as the parent storage backend. Privileges are shown only on the cluster-based storage backends. If you add SVM as the storage backend, privileges information will not be shown.

The Interface tab provides detailed information about the interface.

The Local Tiers tab provides detailed information about the aggregate list.

